name: "setup"
description: "setup"
inputs:
  token:
    description: "GitHub token"
    required: true
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: toyfield/pkg-a
        path: pkg-a
        token: ${{ inputs.token }}
    - uses: pnpm/action-setup@v4
      with:
        package_json_file: pkg-a/package.json
    - run: 
        echo $(pwd)
      shell: bash
      working-directory: pkg-a
    - uses: actions/setup-node@v4
      with:
        registry-url: https://npm.pkg.github.com/
        node-version: 22.x
        cache: pnpm
        cache-dependency-path: pkg-a/pnpm-lock.yaml
    - run:
        pnpm install
      shell: bash
      working-directory: pkg-a